//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.Pictures = new HashSet<Pictures>();
        }
    
        public int Event_Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public System.DateTime Event_Start { get; set; }
        public System.DateTime Event_End { get; set; }
        public bool IsEventPublic { get; set; }
        public string Admin_Email { get; set; }
        public int Radius { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
    }
}
